@startuml

(Source Code) -r-> [Lexer]

[Lexer] -> [Parser]

[Parser] -> [AST]

node "HIR" {
    [HIR tree]
    [HIR Session]
}

node "AST Lowering" {
    [AST Validation] -l-> [AST Lowerer]
}

[AST] --> [AST Validation]

[AST Lowerer] --l--> "HIR" : Produces

node "Semantic Analysis" {
    [Identification] --> [TypeChecking]
    [Semantic]
}

[AST Lowering] --> [Identification]
[Semantic] ..l..> "HIR": uses

[TypeChecking] --d-> [LLVM Frontend]

[LLVM Frontend] -d-> (LLVM_IR) : produces
[LLVM Frontend] .....> "HIR" : uses

(LLVM_IR) -r-> (ASM): llc
(ASM) -r-> (EXECUTABLE): C/ASM compiler

[HIR Session] .....> [Memory Arena]: uses
[Semantic] ....l..> [Memory Arena]

@enduml
