[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../../lib/lexer" }
parser = { path = "../../lib/parser" }
ast = { path = "../../lib/ast" }
interpreter = { path = "../../lib/interpreter" }
ast_passes = { path = "../../lib/ast_passes" }
